/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Bloomfield                             */
/*      FILE         :  Bloomfield.cpp                         */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX631                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                
                                                                           
                                                                           
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 08/07/2013                                        */
/************************************************************************/

#include "include/common.hpp"

uint16_t log_cnt = 0;
uint16_t log_sen_ls[LOGSIZE], log_sen_lc[LOGSIZE], log_sen_rc[LOGSIZE], log_sen_rs[LOGSIZE];
float log_v_actual[LOGSIZE], log_v_target[LOGSIZE], log_a_v_actual[LOGSIZE], log_a_v_target[LOGSIZE];

Status::Value Velocity;
Status::Value2 VelocityDiff;
Status::Value2 TargetVelocity;
Status::Value Accel;

Status::Value A_Velocity;
Status::Value2 A_VelocityDiff;
Status::Value2 TargetA_Velocity;
Status::Value A_Accel;

Status::Value2 Degree;
Status::Value2 Distance;
Status::Value2 GyroRef;

Status::Flag ExecuteFlag;
Status::Flag WallPFlag;
Status::Flag WallEdgeFlag;
Status::Flag GyroCtrlFlag;

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void) {
	log_cnt = 0;

	System::SetUp::Clock();
	System::SetUp::IO();
	System::SetUp::Functions();
	System::SetUp::CreateClass();

	System::Timer::Switch(0, 1);
	System::Timer::Switch(1, 1);

	System::Interface::InitLED();
	System::SetUp::StartCheck();

	PWM::Buzzer::Melody_M_Coin();
//	PWM::Buzzer::Melody_FoxMovie();

	while(1) {
		System::Interface::ModeSelect();
		System::Interface::SetLEDColor(0, 0, 255, 0);
		PWM::Buzzer::Melody_TE32_1();
		System::Interface::SetLEDColor(0, 0, 0, 0);

		System::Timer::wait_ms(1000);
		Mystat::Position::Reset();

		switch (System::Interface::GetExecuteMode()) {
			case 1:
				Mystat::Map::Search_Adachi(GOAL_X, GOAL_Y, false, false, false);

				if (ExecuteFlag.GetValue()) {
					Mystat::Map::Search_Adachi(START_X, START_Y, false, true, false);
				}
				break;

			case 2:
				Mystat::Map::Search_Adachi(GOAL_X, GOAL_Y, true, false, false);
				break;

			case 3:
//				Mystat::Map::Search_Adachi(GOAL_X, GOAL_Y, false, false, false);
//				Mystat::Map::SendData();
				Mystat::Map::MakePath(500, 300, 300, 3000, 2500);
				Mystat::Map::ReadPath(500, 300, 300, 3000, 2500);
				break;

			case 4:
				Mystat::Map::MakePath(700, 300, 500, 4500, 2500);
				Mystat::Map::ReadPath(700, 300, 500, 4500, 2500);
				break;

			case 5:
				Mystat::Map::MakePath(1200, 400, 900, 4500, 2500);
				Mystat::Map::ReadPath(1200, 400, 900, 4500, 2500);
				break;

			case 6:
				Mystat::Map::MakePath(1500, 500,1200, 4500, 2500);
				Mystat::Map::ReadPath(1500, 500,1200, 4500, 2500);

//				PWM::Motor::TestSlalom(false);
//				PWM::Motor::TestDetectEdge(false, SLALOM_LEFT);
//				PWM::Motor::TestWheelDiameter();

//				while(1) {
//					sprintf(senddata, "%4d, %4d, %4d, %4d, %4d, %4d, %4d\n", Status::Sensor::GetValue(Status::Sensor::LS, false), Status::Sensor::GetValue(Status::Sensor::LC, false), Status::Sensor::GetValue(Status::Sensor::LF, false), Status::Sensor::GetValue(Status::Sensor::F, false), Status::Sensor::GetValue(Status::Sensor::RF, false), Status::Sensor::GetValue(Status::Sensor::RC, false), Status::Sensor::GetValue(Status::Sensor::RS, false));
//					System::SCI::SendChar(senddata);
//					System::Timer::wait_ms(1000);
//				}

				break;

			case 7:
				if (System::Flash::EraseBlock(BLOCK_DB0)) {
					Mystat::Map::Init();
					System::Interface::SetLEDColor(0, 0, 255, 0);
				} else {
					System::Interface::SetLEDColor(0, 255, 0, 0);
				}
				break;

			default:
				break;
		}

		System::Interface::SetLEDColor(0, 0, 0, 0);
		System::Interface::SetLEDColor(1, 0, 0, 0);
		while(SW_NEXT == 1);
}

	return 0;
}
